# **KNN imputer**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

In [ ]:
df=pd.read_csv('train.csv',usecols=['Age','Pclass','Fare','Survived'])

In [ ]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [ ]:
df.isnull().mean()

Survived    0.000000
Pclass      0.000000
Age         0.198653
Fare        0.000000
dtype: float64

In [ ]:
x=df.drop('Survived',axis=1)
y=df['Survived']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
knn=KNNImputer(n_neighbors=5,weights='distance')
x_train_trf=knn.fit_transform(x_train)
x_test_trf=knn.transform(x_test)

In [ ]:
pd.DataFrame(x_train_trf,columns=x_train.columns)

     Pclass        Age      Fare
0       1.0  40.000000   27.7208
1       3.0   4.000000   16.7000
2       3.0  47.000000    9.0000
3       3.0   9.000000   31.3875
4       3.0  20.000000    9.8458
..      ...        ...       ...
707     3.0  30.000000    8.6625
708     3.0  25.047962    8.7125
709     1.0  71.000000   49.5042
710     1.0  29.530076  221.7792
711     1.0  49.275927   25.9250

[712 rows x 3 columns]

In [ ]:
clf=LogisticRegression()

clf.fit(x_train_trf,y_train)

y_pred=clf.predict(x_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7039106145251397

for MICE see lec no 40